# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'





target 'FlutterCocoaFrameworkTest' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!


  # Pods for UseFlutterModule

#  pod 'Flutter', :podspec => 'FlutterLib/Release/Flutter.podspec'
  pod 'Flutter', :podspec => 'FlutterLib/Debug/Flutter.podspec'

end

